<a href="https://colab.research.google.com/github/Nikhilkumar77817/Data-Science/blob/main/MachineLearning_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Naive Bayes** is a supervised machine learning classification algorithm based on **Bayes' Theorem**.
* It is widely used for text classification, spam filtering, and sentiment analysis due to its high efficiency and scalability

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score , recall_score, accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
heart_data = pd.read_csv("/content/17.heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X = heart_data.drop('target', axis=1)
y = heart_data['target']

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3

In [ ]:
gnb_model = GaussianNB()
gnb_model.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = gnb_model.predict(X_test)

In [ ]:
#evaluation
print("recall score :", recall_score(y_test, y_pred)) # recall is imp for heart data
print("precision score :", precision_score(y_test, y_pred))
print("accuracy score :", accuracy_score(y_test, y_pred))
print("f1 score :", f1_score(y_test, y_pred))

recall score : 0.84375
precision score : 0.9
accuracy score : 0.8688524590163934
f1 score : 0.8709677419354839

**K-Nearest Neighbors (KNN)** is a simple, supervised machine learning algorithm used for both classification and regression

* KNN is called a **"lazy learner"** because it does not have a formal training phase. Instead, it stores the entire training dataset and performs all calculations only when a new prediction is requested

* **Distance Metrics:** The "closeness" is calculated using metrics such as Euclidean Distance (straight-line), Manhattan Distance (grid-like), or Hamming Distance (for categorical data)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score , recall_score, accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
heart_data = pd.read_csv("/content/17.heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X1 = heart_data.drop('target', axis=1)
y1 = heart_data['target']

In [ ]:
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y1, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X1_train_scaled = scaler.fit_transform(X1_train)
X1_test_scaled = scaler.transform(X1_test)

In [ ]:
X1_train_scaled

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [ ]:
# for k = 3
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X1_train_scaled, y1_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y1_pred = knn_classifier.predict(X1_test_scaled)

print("recall score :", recall_score(y1_test, y1_pred))
print("precision score :", precision_score(y1_test, y1_pred))
print("accuracy score :", accuracy_score(y1_test, y1_pred))

recall score : 0.78125
precision score : 0.9259259259259259
accuracy score : 0.8524590163934426

In [ ]:
# for k = 5
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X1_train_scaled, y1_train)

KNeighborsClassifier()

In [ ]:
y1_pred = knn_classifier.predict(X1_test_scaled)

print("recall score :", recall_score(y1_test, y1_pred))
print("precision score :", precision_score(y1_test, y1_pred))
print("accuracy score :", accuracy_score(y1_test, y1_pred))

recall score : 0.875
precision score : 0.9333333333333333
accuracy score : 0.9016393442622951

In [ ]:
# for k = 7
knn_classifier = KNeighborsClassifier(n_neighbors=7)
knn_classifier.fit(X1_train_scaled, y1_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y1_pred = knn_classifier.predict(X1_test_scaled)

print("recall score :", recall_score(y1_test, y1_pred))
print("precision score :", precision_score(y1_test, y1_pred))
print("accuracy score :", accuracy_score(y1_test, y1_pred))

recall score : 0.90625
precision score : 0.9354838709677419
accuracy score : 0.9180327868852459

**Cross-validation (CV)** is a statistical resampling technique used to evaluate how well a machine learning model generalizes to unseen data.
* It protects against overfitting—where a model performs well on training data but poorly on new data—by ensuring every data point is used for both training and testing across multiple iterations.

* **Hyperparameter Tuning:** It is frequently used to find the optimal values for model settings (like the depth of a decision tree) without "peeking" at the final test set.

In [ ]:
 # Cross Validation for hyperparameter tuning using GridSearchCV

from sklearn.model_selection import GridSearchCV

classifier = KNeighborsClassifier()
param_grid = {"n_neighbors": [3, 5, 7, 9]}

classifierCV = GridSearchCV(
    classifier,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X1_train_scaled, y1_train)

y1_pred = classifierCV.predict(X1_test_scaled)

print("recall score: ", recall_score(y1_test, y1_pred))
print("accuracy score: ", accuracy_score(y1_test, y1_pred))
print("precision score: ", precision_score(y1_test, y1_pred))

# results
res = pd.DataFrame(classifierCV.cv_results_)
print(res[["param_n_neighbors", "mean_test_score"]])
# print(res)
print(classifierCV.best_params_)

recall score:  0.90625
accuracy score:  0.9180327868852459
precision score:  0.9354838709677419
   param_n_neighbors  mean_test_score
0                  3         0.864387
1                  5         0.857550
2                  7         0.871795
3                  9         0.856980
{'n_neighbors': 7}

In Scikit-learn, a **Pipeline** is a tool that chains multiple data processing steps (transformers) and a final model (estimator) into a single object.

* **Transformers**: Intermediate steps that modify data (e.g., StandardScaler, SimpleImputer, PCA). Every step except the last must implement fit() and transform().
* **Estimator:** The final step in the pipeline, usually a machine learning model (e.g., LogisticRegression, RandomForestClassifier). It must implement fit() and may implement predict().
* Benefits
1. Prevents Data Leakage
2. Simplifies Hyperparameter Tuning
3. Code Reproducibility

In [ ]:
# Pipeline
from sklearn.pipeline import Pipeline

X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y1, test_size=0.2, random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

param_grid = {"knn__n_neighbors": [3, 5, 7, 9]} # double udesocre show heirarchical n_neighbour inside knn

classifierCV = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X1_train, y1_train)

y1_pred = classifierCV.predict(X1_test)

print("recall score: ", recall_score(y1_test, y1_pred))
print("accuracy score: ", accuracy_score(y1_test, y1_pred))
print("precision score: ", precision_score(y1_test, y1_pred))

print(classifierCV.best_params_)

recall score:  0.90625
accuracy score:  0.9180327868852459
precision score:  0.9354838709677419
{'knn__n_neighbors': 7}